CREATE TABLE Accounts (
  ACC_NUM2 int(11) NOT NULL,
  OPINING_DATE date NOT NULL,
  TRAN_REF int(6) NOT NULL,
  Balance decimal(10,0) NOT NULL,
  Acc varchar(1) COLLATE utf8_bin DEFAULT NULL,
  Account_name char(50) COLLATE utf8_bin NOT NULL,
  AMOUNT decimal(9,2) NOT NULL,
MONEY varchar(3) default 000,
Account_name1 varchar(30) COLLATE utf8_bin DEFAULT NULL,
  Account_number varchar(8) COLLATE utf8_bin DEFAULT NULL,
  Account_type char(1) COLLATE utf8_bin DEFAULT NULL,
  Account_status varchar(6) COLLATE utf8_bin DEFAULT NULL,
  TRANSACTION_date date DEFAULT NULL,
  user_id varchar(5) COLLATE utf8_bin DEFAULT NULL,
  Mount varchar(9) COLLATE utf8_bin DEFAULT NULL,
  cruncy varchar(3) COLLATE utf8_bin DEFAULT NULL,
  Cridet double DEFAULT NULL,
  Debit double DEFAULT NULL,
  balance int(11) DEFAULT NULL,

BGoV int(2) NOT NULL,
  BTYP int(2) NOT NULL,
  Boffice int(2) NOT NULL,
  BAccont int(2) NOT NULL,
  discrip varchar(50) DEFAULT NULL,
  ice varchar(50) DEFAULT NULL,
  BBD int(1) DEFAULT NULL,
  BBF int(1) DEFAULT NULL,
  balance varchar(12) DEFAULT NULL,
  tareekh datetime DEFAULT NULL,
  chakun int(3) DEFAULT NULL,

PAGE_HREF varchar(50) DEFAULT NULL,
  pro varchar(20) DEFAULT NULL,
  PRIVIL_VAL char(1) DEFAULT NULL,
  email varchar(50) DEFAULT NULL,
  IDNTITY int(9) DEFAULT NULL,
  PAGE_LINK varchar(50) DEFAULT NULL,
,

PAGE_HREF varchar(50) DEFAULT NULL,
  pro varchar(20) DEFAULT NULL,
  PRIVIL_VAL char(1) DEFAULT NULL,
  email varchar(50) DEFAULT NULL,
  IDNTITY int(9) DEFAULT NULL,
  PAGE_LINK varchar(50) DEFAULT NULL,

IDNTITY varchar(9) DEFAULT NULL,
  email varchar(20) DEFAULT NULL,
Actnam varchar(30) NOT NULL,
  LEDnm varchar(4) NOT NULL,
  Balance2 int(11) NOT NULL,


  TRAN_REF int(6) DEFAULT NULL,
  Acc varchar(1) DEFAULT NULL,
  Account_name2 char(50) DEFAULT NULL,
  AMOUNT decimal(9,2) DEFAULT NULL,
  LEDnm1 varchar(4) NOT NULL,
  balanced int(11) DEFAULT NULL,
  ACC_NUMB varchar(11) DEFAULT NULL,

ACC_NUM1 varchar(9) DEFAULT NULL,
  LEDnm2 varchar(4) DEFAULT NULL,
  ACC_NUMC varchar(9) DEFAULT NULL,
  LEDnmc varchar(4) DEFAULT NULL,
  Tran_DATE datetime DEFAULT NULL,
  Balance3 int(11) DEFAULT NULL,
  Acc varchar(10) DEFAULT NULL,
  Account_name3 varchar(30) DEFAULT NULL,
  Money int(11) DEFAULT NULL,
  total_9001 varchar(11) DEFAULT NULL,
  total_9002 varchar(11) DEFAULT NULL,
  total_9003 varchar(10) DEFAULT NULL,
  total_8001 varchar(11) DEFAULT NULL,
  total_8002 varchar(11) DEFAULT NULL,
  total_1001 varchar(11) DEFAULT NULL,

GiDG int(4) NOT NULL DEFAULT '0',
  Actnm varchar(9) DEFAULT NULL,
  LEDnm3 varchar(4) DEFAULT NULL,
  wasf varchar(100) DEFAULT NULL,
  Actnmc varchar(9) DEFAULT NULL,
  LEDnmc varchar(4) DEFAULT NULL,
  TRANSACTION_date varchar(30) DEFAULT NULL,
  cruncy varchar(4) DEFAULT NULL,
  AC_Cridet varchar(9) DEFAULT NULL,
  Debit varchar(9) DEFAULT NULL,
   IDNTITY varchar(9) DEFAULT NULL,
  class_vication int(11) NOT NULL
)